## Feature normalization

In [25]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

def preprocess(x, y):
    x = tf.cast(x, tf.float32) / 255.0
    y = tf.cast(y, tf.int64)
    return x, y


def create_dataset(xs, ys, n_classes=10):
    ys = tf.one_hot(ys, depth=n_classes)
    return tf.data.Dataset.from_tensor_slices((xs, ys)).map(preprocess).shuffle(len(ys)).batch(128)
    
    
def normalize(x, axes=[0], epsilon=1e-8):
    mean, variance = tf.nn.moments(x, axes=axes)
    x_normed = (x - mean) / tf.sqrt(variance + epsilon) # epsilon to avoid dividing by zero
    tf.print('mean:', mean)
    tf.print('varince:', variance)
    return x_normed


def preprocess(x, y):
    x = tf.cast(x, tf.float32)
    x_normed = normalize(x)
    y = tf.cast(y, tf.int64)
    return x_normed, y


def create_dataset(xs, ys, n_classes=3):
    ys = tf.one_hot(ys, depth=n_classes)
    # return tf.data.Dataset.from_tensor_slices((xs, ys)).map(preprocess).shuffle(len(ys)).batch(128)
    return tf.data.Dataset.from_tensor_slices((xs, ys)).map(preprocess)


x = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
y = tf.constant([0,1,2])

train_dataset = create_dataset(x, y)

for x, y in train_dataset:
    print(x, y)

mean: 2
varince: 0.666666687
tf.Tensor([-1.2247448  0.         1.2247448], shape=(3,), dtype=float32) tf.Tensor([1 0 0], shape=(3,), dtype=int64)
mean: 3
varince: 0.666666687
tf.Tensor([-1.2247448  0.         1.2247448], shape=(3,), dtype=float32) tf.Tensor([0 1 0], shape=(3,), dtype=int64)
mean: 4
varince: 0.666666687
tf.Tensor([-1.2247448  0.         1.2247448], shape=(3,), dtype=float32) tf.Tensor([0 0 1], shape=(3,), dtype=int64)
